services:
  app:
    container_name: dockerSample
    build: .
    ports:
        - "8080:8085"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=infosmart@1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: infosmart@1
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"


