server.port=8085
spring.application.name=sampleDockerImpl
spring.datasource.url=jdbc:postgresql://172.16.1.16:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=infosmart@1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



